---
driver:
  name: docker
  use_sudo: false
  privileged: true
  require_chef_omnibus: false

verifier:
  name: inspec
  inspec_tests:
    - test/integration/cluster/inspec

platforms:
  - name: leap-15
    driver_config:
      image: opensuse/leap:15
      run_command: /usr/lib/systemd/systemd
      provision_command:
        - systemctl enable sshd.service
provisioner:
  name: salt_solo
  require_chef: false
  formula: cluster
  state_top:
    base:
      '*':
        - cluster
  pillars-from-files:
    base.sls: pillar.example
  pillars:
    top.sls:
      base:
        '*':
          - base
          - cluster

suites:
  - name: cluster-init
    provisioner:
      pillars:
        cluster.sls:
          cluster:
            mode: init
