---
driver:
  name: docker
  use_sudo: false
  privileged: true
  require_chef_omnibus: false
  run_command: /usr/lib/systemd/systemd
  cap_add:
    - SYS_ADMIN
  volume:
    - /sys/fs/cgroup    

verifier:
  name: inspec
  inspec_tests:
    - test/integration/cluster/inspec

platforms:
  - name: opensuse
    driver_config:
      image: opensuse/leap:15
      platform: opensuse
      run_command: /usr/lib/systemd/systemd
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable sshd
        - zypper -n --gpg-auto-import-keys in crmsh resource-agents fence-agents salt
provisioner:
  name: salt_solo
  require_chef: false
  formula: cluster
  salt_install: distrib
  state_top:
    base:
      '*':
        - cluster
  pillars-from-files:
    base.sls: pillar.example
  pillars:
    top.sls:
      base:
        '*':
          - base
          - cluster

suites:
  - name: cluster-init
    provisioner:
      pillars:
        cluster.sls:
          cluster:
            mode: init
